In [1]:
import numpy as np 
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.utils
import random

In [2]:
df_G_0_Checked_points = pd.read_csv('Cross_df_G_0_Checked_points.csv')
df_G_1_Checked_points = pd.read_csv('Cross_df_G_1_Checked_points.csv')
df_G_2_Checked_points = pd.read_csv('Cross_df_G_2_Checked_points.csv')
df_G_3_Checked_points = pd.read_csv('Cross_df_G_3_Checked_points.csv')
df_G_n1_Checked_points = pd.read_csv('Cross_df_G_n1_Checked_points.csv')

In [20]:
two_D_Data_G_0 = df_G_0_Checked_points[["LAT", "LON"]]
# two_D_Data_G_0 = StandardScaler().fit_transform(two_D_Data_G_0)
two_D_Data_G_0.shape
two_D_covMatrix_G_0 = np.cov(two_D_Data_G_0.T,bias=True)
I_G_0 = np.matrix(two_D_covMatrix_G_0).I
mean_G_0 = two_D_Data_G_0.mean(axis = 0) 

In [21]:
two_D_Data_G_1 = df_G_1_Checked_points[["LAT", "LON"]]
# two_D_Data_G_1 = StandardScaler().fit_transform(two_D_Data_G_1)
two_D_Data_G_1.shape
two_D_covMatrix_G_1 = np.cov(two_D_Data_G_1.T,bias=True)
I_G_1 = np.matrix(two_D_covMatrix_G_1).I
mean_G_1 = two_D_Data_G_1.mean(axis = 0) 

In [22]:
two_D_Data_G_2 = df_G_2_Checked_points[["LAT", "LON"]]
# two_D_Data_G_2 = StandardScaler().fit_transform(two_D_Data_G_2)
two_D_Data_G_2.shape
two_D_covMatrix_G_2 = np.cov(two_D_Data_G_2.T,bias=True)
I_G_2 = np.matrix(two_D_covMatrix_G_2).I
mean_G_2 = two_D_Data_G_2.mean(axis = 0) 

In [23]:
two_D_Data_G_3 = df_G_3_Checked_points[["LAT", "LON"]]
# two_D_Data_G_3 = StandardScaler().fit_transform(two_D_Data_G_3)
two_D_Data_G_3.shape
two_D_covMatrix_G_3 = np.cov(two_D_Data_G_3.T,bias=True)
I_G_3 = np.matrix(two_D_covMatrix_G_3).I
mean_G_3 = two_D_Data_G_3.mean(axis = 0) 

In [24]:
two_D_Data_G_4 = df_G_4_Checked_points[["LAT", "LON"]]
# two_D_Data_G_4 = StandardScaler().fit_transform(two_D_Data_G_4)
two_D_Data_G_4.shape
two_D_covMatrix_G_4 = np.cov(two_D_Data_G_4.T,bias=True)
I_G_4 = np.matrix(two_D_covMatrix_G_4).I
mean_G_4 = two_D_Data_G_4.mean(axis = 0) 

In [25]:
two_D_Data_G_n1 = df_G_n1_Checked_points[["LAT", "LON"]]
# two_D_Data_G_n1 = StandardScaler().fit_transform(two_D_Data_G_n1)
two_D_Data_G_n1.shape
two_D_covMatrix_G_n1 = np.cov(two_D_Data_G_n1.T,bias=True)
I_G_n1 = np.matrix(two_D_covMatrix_G_n1).I
mean_G_n1 = two_D_Data_G_n1.mean(axis = 0) 

In [9]:
# #############################################################################
# Read data & generate checked points for each label 
file_url = 'rotated_filtered_2.csv'
df = pd.read_csv(file_url)
df.shape[0]

1598

In [27]:
df['label'] = -2
for i in range(df.shape[0]):
    point = df.iloc[i]
    point_two_D = point[["LAT", "LON"]]
    dist_G_0 = np.dot(np.dot((point_two_D - mean_G_0), I_G_0), (point_two_D - mean_G_0).T)[0,0] ** 0.5
    dist_G_1 = np.dot(np.dot((point_two_D - mean_G_1), I_G_1), (point_two_D - mean_G_1).T)[0,0] ** 0.5
    dist_G_2 = np.dot(np.dot((point_two_D - mean_G_2), I_G_2), (point_two_D - mean_G_2).T)[0,0] ** 0.5
    dist_G_3 = np.dot(np.dot((point_two_D - mean_G_3), I_G_3), (point_two_D - mean_G_3).T)[0,0] ** 0.5
    dist_G_4 = np.dot(np.dot((point_two_D - mean_G_4), I_G_4), (point_two_D - mean_G_4).T)[0,0] ** 0.5
    dist_G_n1 = np.dot(np.dot((point_two_D - mean_G_n1), I_G_n1), (point_two_D - mean_G_n1).T)[0,0] ** 0.5
    dist_list = [dist_G_0, dist_G_1, dist_G_2, dist_G_3, dist_G_4, dist_G_n1]
    min_idx = dist_list.index(min(dist_list))
    if min(dist_list) < 6:
        df.loc[i, 'label'] = min_idx
    else:
        df.loc[i, 'label'] = -1


In [28]:
df.to_csv('result_31.csv')

In [29]:
df['label'].unique()

array([4, 0, 3, 1, 2, 5], dtype=int64)

In [3]:
five_D_Data_G_0 = df_G_0_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_0 = StandardScaler().fit_transform(five_D_Data_G_0)
five_D_Data_G_0.shape
five_D_covMatrix_G_0 = np.cov(five_D_Data_G_0.T,bias=True)
I_G_0 = np.matrix(five_D_covMatrix_G_0).I
mean_G_0 = five_D_Data_G_0.mean(axis = 0) 

In [4]:
five_D_Data_G_1 = df_G_1_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_1 = StandardScaler().fit_transform(five_D_Data_G_1)
five_D_Data_G_1.shape
five_D_covMatrix_G_1 = np.cov(five_D_Data_G_1.T,bias=True)
I_G_1 = np.matrix(five_D_covMatrix_G_1).I
mean_G_1 = five_D_Data_G_1.mean(axis = 0) 

In [5]:
five_D_Data_G_2 = df_G_2_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_2 = StandardScaler().fit_transform(five_D_Data_G_2)
five_D_Data_G_2.shape
five_D_covMatrix_G_2 = np.cov(five_D_Data_G_2.T,bias=True)
I_G_2 = np.matrix(five_D_covMatrix_G_2).I
mean_G_2 = five_D_Data_G_2.mean(axis = 0) 

In [6]:
five_D_Data_G_3 = df_G_3_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_3 = StandardScaler().fit_transform(five_D_Data_G_3)
five_D_Data_G_3.shape
five_D_covMatrix_G_3 = np.cov(five_D_Data_G_3.T,bias=True)
I_G_3 = np.matrix(five_D_covMatrix_G_3).I
mean_G_3 = five_D_Data_G_3.mean(axis = 0) 

In [7]:
five_D_Data_G_n1 = df_G_n1_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_n1 = StandardScaler().fit_transform(five_D_Data_G_n1)
five_D_Data_G_n1.shape
five_D_covMatrix_G_n1 = np.cov(five_D_Data_G_n1.T,bias=True)
I_G_n1 = np.matrix(five_D_covMatrix_G_n1).I
mean_G_n1 = five_D_Data_G_n1.mean(axis = 0) 

In [11]:
df['label'] = -2
for i in range(df.shape[0]):
    point = df.iloc[i]
    point_five_D = point[["LAT", "LON", "Heading"]]    
    dist_G_0 = np.dot(np.dot((point_five_D - mean_G_0), I_G_0), (point_five_D - mean_G_0).T)[0,0] ** 0.5
    dist_G_1 = np.dot(np.dot((point_five_D - mean_G_1), I_G_1), (point_five_D - mean_G_1).T)[0,0] ** 0.5
    dist_G_2 = np.dot(np.dot((point_five_D - mean_G_2), I_G_2), (point_five_D - mean_G_2).T)[0,0] ** 0.5
    dist_G_3 = np.dot(np.dot((point_five_D - mean_G_3), I_G_3), (point_five_D - mean_G_3).T)[0,0] ** 0.5
    dist_G_n1 = np.dot(np.dot((point_five_D - mean_G_n1), I_G_n1), (point_five_D - mean_G_n1).T)[0,0] ** 0.5
    dist_list = [dist_G_0, dist_G_1, dist_G_2, dist_G_3, dist_G_n1]
    min_idx = dist_list.index(min(dist_list))
    if min(dist_list) < 6:
        df.loc[i, 'label'] = min_idx
    else:
        df.loc[i, 'label'] = -1
df.to_csv('result_32.csv')

In [12]:
df['label'].unique()

array([ 0,  1,  2,  3,  4, -1], dtype=int64)

In [59]:
# #############################################################################
# Read data
file_url = 'Testing_Data_dup.csv'
df = pd.read_csv(file_url)
df.head()

C:\Users\62707\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


MMSI         BaseDateTime       LAT       LON  SOG   COG  Heading  \
0  316013007  2017-01-01T00:01:10  44.23262 -76.47704 -0.1 -49.6      100   
1  316013007  2017-01-01T00:02:17  44.23264 -76.47541 -0.1 -49.6      120   
2  316013007  2017-01-01T00:03:25  44.23064 -76.47384 -0.1 -49.6      172   
3  316013007  2017-01-01T00:04:27  44.22846 -76.47331 -0.1 -49.6      179   
4  316013007  2017-01-01T00:05:38  44.22577 -76.47337 -0.1 -49.6      184   

           VesselName         IMO CallSign VesselType                  Status  \
0  WOLFE ISLANDER III  IMO7423079   VA3418       1018  under way using engine   
1  WOLFE ISLANDER III  IMO7423079   VA3418       1018  under way using engine   
2  WOLFE ISLANDER III  IMO7423079   VA3418       1018  under way using engine   
3  WOLFE ISLANDER III  IMO7423079   VA3418       1018  under way using engine   
4  WOLFE ISLANDER III  IMO7423079   VA3418       1018  under way using engine   

   Length  Width  Draft  Cargo  
0   62.49  20.27    2.3     60  
1   62.49  20.27    2.3     60  
2   62.49  20.27    2.3     60  
3   62.49  20.27    2.3     60  
4   62.49  20.27    2.3     60

In [60]:
df.shape

(39891, 16)

In [61]:
df_G_0_Checked_points = pd.read_csv('Noise_df_G_0_Checked_points.csv')
df_G_1_Checked_points = pd.read_csv('Noise_df_G_1_Checked_points.csv')
df_G_2_Checked_points = pd.read_csv('Noise_df_G_2_Checked_points.csv')
df_G_3_Checked_points = pd.read_csv('Noise_df_G_3_Checked_points.csv')
df_G_4_Checked_points = pd.read_csv('Noise_df_G_4_Checked_points.csv')

In [62]:
five_D_Data_G_0 = df_G_0_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_0 = StandardScaler().fit_transform(five_D_Data_G_0)
five_D_Data_G_0.shape
five_D_covMatrix_G_0 = np.cov(five_D_Data_G_0.T,bias=True)
I_G_0 = np.matrix(five_D_covMatrix_G_0).I
mean_G_0 = five_D_Data_G_0.mean(axis = 0) 

In [63]:
five_D_Data_G_1 = df_G_1_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_1 = StandardScaler().fit_transform(five_D_Data_G_1)
five_D_Data_G_1.shape
five_D_covMatrix_G_1 = np.cov(five_D_Data_G_1.T,bias=True)
I_G_1 = np.matrix(five_D_covMatrix_G_1).I
mean_G_1 = five_D_Data_G_1.mean(axis = 0) 

In [64]:
five_D_Data_G_2 = df_G_2_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_2 = StandardScaler().fit_transform(five_D_Data_G_2)
five_D_Data_G_2.shape
five_D_covMatrix_G_2 = np.cov(five_D_Data_G_2.T,bias=True)
I_G_2 = np.matrix(five_D_covMatrix_G_2).I
mean_G_2 = five_D_Data_G_2.mean(axis = 0) 

In [65]:
five_D_Data_G_3 = df_G_3_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_3 = StandardScaler().fit_transform(five_D_Data_G_3)
five_D_Data_G_3.shape
five_D_covMatrix_G_3 = np.cov(five_D_Data_G_3.T,bias=True)
I_G_3 = np.matrix(five_D_covMatrix_G_3).I
mean_G_3 = five_D_Data_G_3.mean(axis = 0) 

In [66]:
five_D_Data_G_4 = df_G_4_Checked_points[["LAT", "LON", "Heading"]]
# five_D_Data_G_4 = StandardScaler().fit_transform(five_D_Data_G_4)
five_D_Data_G_4.shape
five_D_covMatrix_G_4 = np.cov(five_D_Data_G_4.T,bias=True)
I_G_4 = np.matrix(five_D_covMatrix_G_4).I
mean_G_4 = five_D_Data_G_4.mean(axis = 0) 

In [67]:
df['label'] = -2
for i in range(df.shape[0]):
    point = df.iloc[i]
    point_five_D = point[["LAT", "LON", "Heading"]]    
    dist_G_0 = np.dot(np.dot((point_five_D - mean_G_0), I_G_0), (point_five_D - mean_G_0).T)[0,0] ** 0.5
    dist_G_1 = np.dot(np.dot((point_five_D - mean_G_1), I_G_1), (point_five_D - mean_G_1).T)[0,0] ** 0.5
    dist_G_2 = np.dot(np.dot((point_five_D - mean_G_2), I_G_2), (point_five_D - mean_G_2).T)[0,0] ** 0.5
    dist_G_3 = np.dot(np.dot((point_five_D - mean_G_3), I_G_3), (point_five_D - mean_G_3).T)[0,0] ** 0.5
    dist_G_4 = np.dot(np.dot((point_five_D - mean_G_4), I_G_4), (point_five_D - mean_G_4).T)[0,0] ** 0.5
    dist_list = [dist_G_0, dist_G_1, dist_G_2, dist_G_3, dist_G_4]
    min_idx = dist_list.index(min(dist_list))
    if min(dist_list) < 6:
        df.loc[i, 'label'] = min_idx
    else:
        df.loc[i, 'label'] = -1
df.to_csv('result_33.csv')

In [68]:
df['label'].unique()

array([ 0, -1,  1,  2,  3,  4], dtype=int64)