In [1]:
import numpy as np 
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.utils

In [2]:
# #############################################################################
# Read data
file_url = 'rotated.csv'
df = pd.read_csv(file_url)
df = df[df['LAT']<=44.234]
df.head()

MMSI         BaseDateTime       LAT       LON  SOG   COG  Heading  \
0  316013007  2017-01-01T00:05:38  44.22577 -76.47337 -0.1 -49.6    184.0   
2  316013007  2017-01-01T00:14:16  44.21882 -76.44503 -0.1 -49.6    105.0   
3  316013007  2017-01-01T00:14:16  44.21146 -76.45525 -0.1 -49.6    195.0   
4  316013007  2017-01-01T00:23:56  44.21536 -76.42605 -0.1 -49.6    116.0   
5  316013007  2017-01-01T00:23:56  44.19248 -76.45871 -0.1 -49.6    206.0   

           VesselName         IMO CallSign          VesselType  \
0  WOLFE ISLANDER III  IMO7423079   VA3418  WOLFE ISLANDER III   
2  WOLFE ISLANDER III  IMO7423079   VA3418  WOLFE ISLANDER III   
3  WOLFE ISLANDER III  IMO7423079   VA3418  WOLFE ISLANDER III   
4  WOLFE ISLANDER III  IMO7423079   VA3418  WOLFE ISLANDER III   
5  WOLFE ISLANDER III  IMO7423079   VA3418  WOLFE ISLANDER III   

                   Status  Length  Width  Draft  Cargo  
0  under way using engine   62.49  20.27    2.3     60  
2  under way using engine   62.49  20.27    2.3     60  
3  under way using engine   62.49  20.27    2.3     60  
4  under way using engine   62.49  20.27    2.3     60  
5  under way using engine   62.49  20.27    2.3     60

In [22]:
two_D_Data = df[["LAT", "LON"]]
two_D_Data = StandardScaler().fit_transform(two_D_Data)
two_D_Data.shape
two_D_covMatrix = np.cov(two_D_Data.T,bias=True)
print (two_D_covMatrix)

[[ 1.         -0.16984848]
 [-0.16984848  1.        ]]


In [23]:
five_D_Data = df[["LAT", "LON", "SOG", "COG", "Heading"]]
five_D_Data = StandardScaler().fit_transform(five_D_Data)
five_D_covMatrix = np.cov(five_D_Data.T,bias=True)
print (five_D_covMatrix)

[[ 1.         -0.16984848  0.          0.         -0.70702397]
 [-0.16984848  1.          0.          0.         -0.21823358]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [-0.70702397 -0.21823358  0.          0.          1.        ]]


In [21]:
two_D_Data = df[["LAT", "LON"]]
two_D_Data = StandardScaler().fit_transform(two_D_Data)
two_D_Data.T

array([[ 0.86869818,  0.36323823, -0.17204021, ...,  0.49996697,
         0.39960226,  0.36032911],
       [-1.1887128 ,  0.43261896, -0.15206737, ..., -0.15035107,
         0.01384166, -0.12346237]])

In [15]:
five_D_covMatrix.shape

(5, 5)